// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBny5EOPvZmOjVde0qaXWvR8hY_VYBs37w',
    appId: '1:873366285246:web:518f0c74b6e115bbc227ef',
    messagingSenderId: '873366285246',
    projectId: 'clinicfinder-b4bef',
    authDomain: 'clinicfinder-b4bef.firebaseapp.com',
    storageBucket: 'clinicfinder-b4bef.appspot.com',
    measurementId: 'G-DR6DXQXET2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_uOQxybNWT2j-IOjniVh59ZZNgJUX7c',
    appId: '1:873366285246:android:a8cb2b2bf0ad672dc227ef',
    messagingSenderId: '873366285246',
    projectId: 'clinicfinder-b4bef',
    storageBucket: 'clinicfinder-b4bef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4NvDxee7gSVm1UZ17kyAxROtnMS1Ehc',
    appId: '1:873366285246:ios:7afcde6a71dd1705c227ef',
    messagingSenderId: '873366285246',
    projectId: 'clinicfinder-b4bef',
    storageBucket: 'clinicfinder-b4bef.firebasestorage.app',
    iosBundleId: 'com.example.clinicfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV4NvDxee7gSVm1UZ17kyAxROtnMS1Ehc',
    appId: '1:873366285246:ios:7afcde6a71dd1705c227ef',
    messagingSenderId: '873366285246',
    projectId: 'clinicfinder-b4bef',
    storageBucket: 'clinicfinder-b4bef.firebasestorage.app',
    iosBundleId: 'com.example.clinicfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBny5EOPvZmOjVde0qaXWvR8hY_VYBs37w',
    appId: '1:873366285246:web:518f0c74b6e115bbc227ef',
    messagingSenderId: '873366285246',
    projectId: 'clinicfinder-b4bef',
    authDomain: 'clinicfinder-b4bef.firebaseapp.com',
    storageBucket: 'clinicfinder-b4bef.appspot.com',
    measurementId: 'G-TDTBYFPBSS',
  );
}
